<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;

use App\Events\NewRegisterEvent;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Log;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];


//    public function setNameAttribute($name)
//    {
//        $this->attributes['name'] = strtoupper($name);
//    }
//
//    public function getNameAttribute()
//    {
//        return strtoupper($this->attributes['name']);
//    }


//    protected function name() : Attribute
//    {
//        return Attribute::make(
//            get: fn($value) => strtolower($value),
//            set: fn($value) => strtoupper($value)
//        );
//    }


    public function role()
    {
        return $this->belongsTo(Role::class);
    }


//    public static function boot()
//    {
//        parent::boot(); // TODO: Change the autogenerated stub
//
//        static::created(function ($user){
//            NewRegisterEvent::dispatch();
//        });
//    }
}
